### ISSUE TITLE
todo / issues

### ISSUE THREAD

**Issue by ghost** [hemidactylus/flaskbiblio#1]
Hey @hemidactylus 

this is an very interesting idea and I would like to contribute! 
I see you have a TODO file, but I don't know what you are working on and if there are things I could do.

Maybe we can make issues for the things that need to be done and work from that?

Thanks! 👍

**Comment by hemidactylus** [comment]
Hi @rjrhaverkamp ,
thank you for your interest. Yes, I admit the TODO is a bit messy. This is a hobby project, mainly an excuse to learn a bit of Flask (and related things such as gunicorn or other deploy tools). I am advancing it at irregular times, depending on my free time.
If you are still interested tell me and we can discuss a bit more what to do and how.
Cheers,
Stefano

**Comment by ghost** [comment]
hi @hemidactylus 

I understand, but I read a lot of books myself so I am interested in this project.

Let me know if I can do something!

🎉

**Comment by hemidactylus** [comment]
Hi, Rob!
Are you still interested in contributing or even just adapting the code to your needs? If so, I'll try and write a (minimal) readme to help you - and possibly others - to know your way around the code.
At the moment, the features I wanted to add to the project are basically there; what I miss is a decent UI.
Do you have had a look at the code? Are you interested in doing so? Perhaps your contribution could be in the UI part? (see below)

Right now the full thing runs with static pages only (and in just a couple places did I have to do some ugly things), I am not sure how soon (or whether) there'll be a proper separation of, say, a javascript interface vs. a backend-only flask set of endpoints. I could head in the direction of Vue.js (which I don't know yet) or something else.

As a first attempt, I am about to put some bootstrap (which I don't know yet either) in the thing and see if this satisfies me.

Hear from you soon!
